### ISSUE TITLE
点击表头筛选控件的时候，报错

### ISSUE THREAD

**Issue by seabiscuityj** [Westsyan/bootstrap-advanced-sortable#5]
可以看到表头筛选控件，但是点击后没有反应，而且浏览器Console输出：

> Uncaught SyntaxError: Unexpected end of JSON input
>     at JSON.parse (<anonymous>)
>     at HTMLButtonElement.<anonymous> (bootstrap-advanced-sortable.js:456:73)
>     at HTMLDivElement.dispatch (jquery.min.js:2:42571)
>     at v.handle (jquery.min.js:2:40572)

**Comment by seabiscuityj** [comment]
> 可以看到表头筛选控件，但是点击后没有反应，而且浏览器Console输出：
> 
> > Uncaught SyntaxError: Unexpected end of JSON input
> > at JSON.parse ()
> > at HTMLButtonElement. (bootstrap-advanced-sortable.js:456:73)
> > at HTMLDivElement.dispatch (jquery.min.js:2:42571)
> > at v.handle (jquery.min.js:2:40572)
将bootstrap-table的search属性设置为fasle后，报错消失。貌似是bootstrap-table自带的搜索框和sortable控件的搜索框冲突？

**Comment by Westsyan** [comment]
1.这个可能是因为你传入的json格式有问题，在初始化控件时我用了JSON.parse()函数；
2.可以同时使用bootstrap-table自带的搜索框和本控件，不冲突的，设为false时报错消失，是因为此时控件没有启用
